<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.19"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>CppyABM: /Users/matin/Downloads/testProjs/CppyABM/examples/cpp/build/_deps/pybind11-src/tests/test_exceptions.py Source File</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">CppyABM
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.19 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_d28a4824dc47e487b107a5db32ef43c4.html">examples</a></li><li class="navelem"><a class="el" href="dir_8976e5d03119516083eaca3ddca61311.html">cpp</a></li><li class="navelem"><a class="el" href="dir_eac5761e9dc061e721c20bc0f1e3d3fc.html">build</a></li><li class="navelem"><a class="el" href="dir_1784aa3aa28ad64c0c4036a372ae00ff.html">_deps</a></li><li class="navelem"><a class="el" href="dir_0ccba7645dc0c717a2c4b127abb4df60.html">pybind11-src</a></li><li class="navelem"><a class="el" href="dir_b9601079a0c6850eab86c0b9d1e0a8a1.html">tests</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">test_exceptions.py</div>  </div>
</div><!--header-->
<div class="contents">
<a href="test__exceptions_8py.html">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno"><a class="line" href="namespacetest__exceptions.html">    1</a></span>&#160;<span class="comment"># -*- coding: utf-8 -*-</span></div>
<div class="line"><a name="l00002"></a><span class="lineno">    2</span>&#160;<span class="keyword">import</span> sys</div>
<div class="line"><a name="l00003"></a><span class="lineno">    3</span>&#160; </div>
<div class="line"><a name="l00004"></a><span class="lineno">    4</span>&#160;<span class="keyword">import</span> pytest</div>
<div class="line"><a name="l00005"></a><span class="lineno">    5</span>&#160; </div>
<div class="line"><a name="l00006"></a><span class="lineno">    6</span>&#160;<span class="keyword">from</span> pybind11_tests <span class="keyword">import</span> exceptions <span class="keyword">as</span> m</div>
<div class="line"><a name="l00007"></a><span class="lineno">    7</span>&#160;<span class="keyword">import</span> pybind11_cross_module_tests <span class="keyword">as</span> cm</div>
<div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160; </div>
<div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160; </div>
<div class="line"><a name="l00010"></a><span class="lineno"><a class="line" href="namespacetest__exceptions.html#a8003f21452ee6d48d5a28cb47ae16bde">   10</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespacetest__exceptions.html#a8003f21452ee6d48d5a28cb47ae16bde">test_std_exception</a>(msg):</div>
<div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;    <span class="keyword">with</span> pytest.raises(RuntimeError) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;        m.throw_std_exception()</div>
<div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;    <span class="keyword">assert</span> <a class="code" href="namespacesetup.html#a52ffe830bc77e7f3621f33f969b6bfee">msg</a>(excinfo.value) == <span class="stringliteral">&quot;This exception was intentionally thrown.&quot;</span></div>
<div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160; </div>
<div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160; </div>
<div class="line"><a name="l00016"></a><span class="lineno"><a class="line" href="namespacetest__exceptions.html#a9ea2bf30538c97fd3968669627212988">   16</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespacetest__exceptions.html#a9ea2bf30538c97fd3968669627212988">test_error_already_set</a>(msg):</div>
<div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;    <span class="keyword">with</span> pytest.raises(RuntimeError) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;        m.throw_already_set(<span class="keyword">False</span>)</div>
<div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;    <span class="keyword">assert</span> <a class="code" href="namespacesetup.html#a52ffe830bc77e7f3621f33f969b6bfee">msg</a>(excinfo.value) == <span class="stringliteral">&quot;Unknown internal error occurred&quot;</span></div>
<div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160; </div>
<div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;    <span class="keyword">with</span> pytest.raises(ValueError) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;        m.throw_already_set(<span class="keyword">True</span>)</div>
<div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;    <span class="keyword">assert</span> <a class="code" href="namespacesetup.html#a52ffe830bc77e7f3621f33f969b6bfee">msg</a>(excinfo.value) == <span class="stringliteral">&quot;foo&quot;</span></div>
<div class="line"><a name="l00024"></a><span class="lineno">   24</span>&#160; </div>
<div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160; </div>
<div class="line"><a name="l00026"></a><span class="lineno"><a class="line" href="namespacetest__exceptions.html#ae7f47864f406f18ce07b0ac482ed3054">   26</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespacetest__exceptions.html#ae7f47864f406f18ce07b0ac482ed3054">test_cross_module_exceptions</a>():</div>
<div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;    <span class="keyword">with</span> pytest.raises(RuntimeError) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;        cm.raise_runtime_error()</div>
<div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;    <span class="keyword">assert</span> <a class="code" href="classstr.html">str</a>(excinfo.value) == <span class="stringliteral">&quot;My runtime error&quot;</span></div>
<div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160; </div>
<div class="line"><a name="l00031"></a><span class="lineno">   31</span>&#160;    <span class="keyword">with</span> pytest.raises(ValueError) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;        cm.raise_value_error()</div>
<div class="line"><a name="l00033"></a><span class="lineno">   33</span>&#160;    <span class="keyword">assert</span> <a class="code" href="classstr.html">str</a>(excinfo.value) == <span class="stringliteral">&quot;My value error&quot;</span></div>
<div class="line"><a name="l00034"></a><span class="lineno">   34</span>&#160; </div>
<div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;    <span class="keyword">with</span> pytest.raises(ValueError) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00036"></a><span class="lineno">   36</span>&#160;        cm.throw_pybind_value_error()</div>
<div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;    <span class="keyword">assert</span> <a class="code" href="classstr.html">str</a>(excinfo.value) == <span class="stringliteral">&quot;pybind11 value error&quot;</span></div>
<div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160; </div>
<div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;    <span class="keyword">with</span> pytest.raises(TypeError) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;        cm.throw_pybind_type_error()</div>
<div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;    <span class="keyword">assert</span> <a class="code" href="classstr.html">str</a>(excinfo.value) == <span class="stringliteral">&quot;pybind11 type error&quot;</span></div>
<div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160; </div>
<div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;    <span class="keyword">with</span> pytest.raises(StopIteration) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;        cm.throw_stop_iteration()</div>
<div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160; </div>
<div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160; </div>
<div class="line"><a name="l00047"></a><span class="lineno"><a class="line" href="namespacetest__exceptions.html#ae6a0bbcfa4d024fd8de0e89bc1bae224">   47</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespacetest__exceptions.html#ae6a0bbcfa4d024fd8de0e89bc1bae224">test_python_call_in_catch</a>():</div>
<div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;    d = {}</div>
<div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;    <span class="keyword">assert</span> m.python_call_in_destructor(d) <span class="keywordflow">is</span> <span class="keyword">True</span></div>
<div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;    <span class="keyword">assert</span> d[<span class="stringliteral">&quot;good&quot;</span>] <span class="keywordflow">is</span> <span class="keyword">True</span></div>
<div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160; </div>
<div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160; </div>
<div class="line"><a name="l00053"></a><span class="lineno"><a class="line" href="namespacetest__exceptions.html#ac7bc0c3050aa0ae201e0800f4bec21f2">   53</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespacetest__exceptions.html#ac7bc0c3050aa0ae201e0800f4bec21f2">ignore_pytest_unraisable_warning</a>(f):</div>
<div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;    unraisable = <span class="stringliteral">&quot;PytestUnraisableExceptionWarning&quot;</span></div>
<div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;    <span class="keywordflow">if</span> <a class="code" href="group__python__builtins.html#gacc0a69f008d341c07ff939e0580c5985">hasattr</a>(pytest, unraisable):  <span class="comment"># Python &gt;= 3.8 and pytest &gt;= 6</span></div>
<div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;        dec = pytest.mark.filterwarnings(<span class="stringliteral">&quot;ignore::pytest.{}&quot;</span>.format(unraisable))</div>
<div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;        <span class="keywordflow">return</span> dec(f)</div>
<div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;    <span class="keywordflow">else</span>:</div>
<div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;        <span class="keywordflow">return</span> f</div>
<div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160; </div>
<div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160; </div>
<div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;@ignore_pytest_unraisable_warning</div>
<div class="line"><a name="l00063"></a><span class="lineno"><a class="line" href="namespacetest__exceptions.html#a2e0d2d2cf645e4c73e4926700aba5788">   63</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespacetest__exceptions.html#a2e0d2d2cf645e4c73e4926700aba5788">test_python_alreadyset_in_destructor</a>(monkeypatch, capsys):</div>
<div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;    hooked = <span class="keyword">False</span></div>
<div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;    triggered = [<span class="keyword">False</span>]  <span class="comment"># mutable, so Python 2.7 closure can modify it</span></div>
<div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160; </div>
<div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;    <span class="keywordflow">if</span> <a class="code" href="group__python__builtins.html#gacc0a69f008d341c07ff939e0580c5985">hasattr</a>(sys, <span class="stringliteral">&quot;unraisablehook&quot;</span>):  <span class="comment"># Python 3.8+</span></div>
<div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;        hooked = <span class="keyword">True</span></div>
<div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;        <span class="comment"># Don&#39;t take `sys.unraisablehook`, as that&#39;s overwritten by pytest</span></div>
<div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;        default_hook = sys.__unraisablehook__</div>
<div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160; </div>
<div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;        <span class="keyword">def </span>hook(unraisable_hook_args):</div>
<div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;            exc_type, exc_value, exc_tb, err_msg, obj = unraisable_hook_args</div>
<div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;            <span class="keywordflow">if</span> obj == <span class="stringliteral">&quot;already_set demo&quot;</span>:</div>
<div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;                triggered[0] = <span class="keyword">True</span></div>
<div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;            default_hook(unraisable_hook_args)</div>
<div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;            <span class="keywordflow">return</span></div>
<div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160; </div>
<div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;        <span class="comment"># Use monkeypatch so pytest can apply and remove the patch as appropriate</span></div>
<div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;        monkeypatch.setattr(sys, <span class="stringliteral">&quot;unraisablehook&quot;</span>, hook)</div>
<div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160; </div>
<div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;    <span class="keyword">assert</span> m.python_alreadyset_in_destructor(<span class="stringliteral">&quot;already_set demo&quot;</span>) <span class="keywordflow">is</span> <span class="keyword">True</span></div>
<div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;    <span class="keywordflow">if</span> hooked:</div>
<div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;        <span class="keyword">assert</span> triggered[0] <span class="keywordflow">is</span> <span class="keyword">True</span></div>
<div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160; </div>
<div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;    _, captured_stderr = capsys.readouterr()</div>
<div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;    <span class="comment"># Error message is different in Python 2 and 3, check for words that appear in both</span></div>
<div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;    <span class="keyword">assert</span> <span class="stringliteral">&quot;ignored&quot;</span> <span class="keywordflow">in</span> captured_stderr <span class="keywordflow">and</span> <span class="stringliteral">&quot;already_set demo&quot;</span> <span class="keywordflow">in</span> captured_stderr</div>
<div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160; </div>
<div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160; </div>
<div class="line"><a name="l00091"></a><span class="lineno"><a class="line" href="namespacetest__exceptions.html#a4e0d71245eded53a1785ca21662e6143">   91</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespacetest__exceptions.html#a4e0d71245eded53a1785ca21662e6143">test_exception_matches</a>():</div>
<div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;    <span class="keyword">assert</span> m.exception_matches()</div>
<div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;    <span class="keyword">assert</span> m.exception_matches_base()</div>
<div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;    <span class="keyword">assert</span> m.modulenotfound_exception_matches_base()</div>
<div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160; </div>
<div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160; </div>
<div class="line"><a name="l00097"></a><span class="lineno"><a class="line" href="namespacetest__exceptions.html#a1e734955761fef2aecda8f88fb97d0c6">   97</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespacetest__exceptions.html#a1e734955761fef2aecda8f88fb97d0c6">test_custom</a>(msg):</div>
<div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;    <span class="comment"># Can we catch a MyException?</span></div>
<div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;    <span class="keyword">with</span> pytest.raises(m.MyException) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;        m.throws1()</div>
<div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;    <span class="keyword">assert</span> <a class="code" href="namespacesetup.html#a52ffe830bc77e7f3621f33f969b6bfee">msg</a>(excinfo.value) == <span class="stringliteral">&quot;this error should go to a custom type&quot;</span></div>
<div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160; </div>
<div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;    <span class="comment"># Can we translate to standard Python exceptions?</span></div>
<div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;    <span class="keyword">with</span> pytest.raises(RuntimeError) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;        m.throws2()</div>
<div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;    <span class="keyword">assert</span> <a class="code" href="namespacesetup.html#a52ffe830bc77e7f3621f33f969b6bfee">msg</a>(excinfo.value) == <span class="stringliteral">&quot;this error should go to a standard Python exception&quot;</span></div>
<div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160; </div>
<div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;    <span class="comment"># Can we handle unknown exceptions?</span></div>
<div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;    <span class="keyword">with</span> pytest.raises(RuntimeError) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;        m.throws3()</div>
<div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;    <span class="keyword">assert</span> <a class="code" href="namespacesetup.html#a52ffe830bc77e7f3621f33f969b6bfee">msg</a>(excinfo.value) == <span class="stringliteral">&quot;Caught an unknown exception!&quot;</span></div>
<div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160; </div>
<div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;    <span class="comment"># Can we delegate to another handler by rethrowing?</span></div>
<div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;    <span class="keyword">with</span> pytest.raises(m.MyException) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;        m.throws4()</div>
<div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;    <span class="keyword">assert</span> <a class="code" href="namespacesetup.html#a52ffe830bc77e7f3621f33f969b6bfee">msg</a>(excinfo.value) == <span class="stringliteral">&quot;this error is rethrown&quot;</span></div>
<div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160; </div>
<div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;    <span class="comment"># Can we fall-through to the default handler?</span></div>
<div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;    <span class="keyword">with</span> pytest.raises(RuntimeError) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;        m.throws_logic_error()</div>
<div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;    <span class="keyword">assert</span> (</div>
<div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;        <a class="code" href="namespacesetup.html#a52ffe830bc77e7f3621f33f969b6bfee">msg</a>(excinfo.value) == <span class="stringliteral">&quot;this error should fall through to the standard handler&quot;</span></div>
<div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;    )</div>
<div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160; </div>
<div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;    <span class="comment"># OverFlow error translation.</span></div>
<div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;    <span class="keyword">with</span> pytest.raises(OverflowError) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;        m.throws_overflow_error()</div>
<div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160; </div>
<div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;    <span class="comment"># Can we handle a helper-declared exception?</span></div>
<div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;    <span class="keyword">with</span> pytest.raises(m.MyException5) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;        m.throws5()</div>
<div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;    <span class="keyword">assert</span> <a class="code" href="namespacesetup.html#a52ffe830bc77e7f3621f33f969b6bfee">msg</a>(excinfo.value) == <span class="stringliteral">&quot;this is a helper-defined translated exception&quot;</span></div>
<div class="line"><a name="l00133"></a><span class="lineno">  133</span>&#160; </div>
<div class="line"><a name="l00134"></a><span class="lineno">  134</span>&#160;    <span class="comment"># Exception subclassing:</span></div>
<div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;    <span class="keyword">with</span> pytest.raises(m.MyException5) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00136"></a><span class="lineno">  136</span>&#160;        m.throws5_1()</div>
<div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;    <span class="keyword">assert</span> <a class="code" href="namespacesetup.html#a52ffe830bc77e7f3621f33f969b6bfee">msg</a>(excinfo.value) == <span class="stringliteral">&quot;MyException5 subclass&quot;</span></div>
<div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;    <span class="keyword">assert</span> <a class="code" href="group__python__builtins.html#gade020f155a1f133cc9e245bac2981280">isinstance</a>(excinfo.value, m.MyException5_1)</div>
<div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160; </div>
<div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;    <span class="keyword">with</span> pytest.raises(m.MyException5_1) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;        m.throws5_1()</div>
<div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;    <span class="keyword">assert</span> <a class="code" href="namespacesetup.html#a52ffe830bc77e7f3621f33f969b6bfee">msg</a>(excinfo.value) == <span class="stringliteral">&quot;MyException5 subclass&quot;</span></div>
<div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160; </div>
<div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;    <span class="keyword">with</span> pytest.raises(m.MyException5) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00145"></a><span class="lineno">  145</span>&#160;        <span class="keywordflow">try</span>:</div>
<div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;            m.throws5()</div>
<div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;        <span class="keywordflow">except</span> m.MyException5_1:</div>
<div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;            <span class="keywordflow">raise</span> RuntimeError(<span class="stringliteral">&quot;Exception error: caught child from parent&quot;</span>)</div>
<div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;    <span class="keyword">assert</span> <a class="code" href="namespacesetup.html#a52ffe830bc77e7f3621f33f969b6bfee">msg</a>(excinfo.value) == <span class="stringliteral">&quot;this is a helper-defined translated exception&quot;</span></div>
<div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160; </div>
<div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160; </div>
<div class="line"><a name="l00152"></a><span class="lineno"><a class="line" href="namespacetest__exceptions.html#a8f1f30a6d37825f9f9b2d48b17c401e1">  152</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespacetest__exceptions.html#a8f1f30a6d37825f9f9b2d48b17c401e1">test_nested_throws</a>(capture):</div>
<div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;    <span class="stringliteral">&quot;&quot;&quot;Tests nested (e.g. C++ -&gt; Python -&gt; C++) exception handling&quot;&quot;&quot;</span></div>
<div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160; </div>
<div class="line"><a name="l00155"></a><span class="lineno">  155</span>&#160;    <span class="keyword">def </span>throw_myex():</div>
<div class="line"><a name="l00156"></a><span class="lineno">  156</span>&#160;        <span class="keywordflow">raise</span> m.MyException(<span class="stringliteral">&quot;nested error&quot;</span>)</div>
<div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160; </div>
<div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;    <span class="keyword">def </span>throw_myex5():</div>
<div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;        <span class="keywordflow">raise</span> m.MyException5(<span class="stringliteral">&quot;nested error 5&quot;</span>)</div>
<div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160; </div>
<div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;    <span class="comment"># In the comments below, the exception is caught in the first step, thrown in the last step</span></div>
<div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160; </div>
<div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;    <span class="comment"># C++ -&gt; Python</span></div>
<div class="line"><a name="l00164"></a><span class="lineno">  164</span>&#160;    <span class="keyword">with</span> capture:</div>
<div class="line"><a name="l00165"></a><span class="lineno">  165</span>&#160;        m.try_catch(m.MyException5, throw_myex5)</div>
<div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;    <span class="keyword">assert</span> <a class="code" href="classstr.html">str</a>(capture).startswith(<span class="stringliteral">&quot;MyException5: nested error 5&quot;</span>)</div>
<div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160; </div>
<div class="line"><a name="l00168"></a><span class="lineno">  168</span>&#160;    <span class="comment"># Python -&gt; C++ -&gt; Python</span></div>
<div class="line"><a name="l00169"></a><span class="lineno">  169</span>&#160;    <span class="keyword">with</span> pytest.raises(m.MyException) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;        m.try_catch(m.MyException5, throw_myex)</div>
<div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;    <span class="keyword">assert</span> <a class="code" href="classstr.html">str</a>(excinfo.value) == <span class="stringliteral">&quot;nested error&quot;</span></div>
<div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160; </div>
<div class="line"><a name="l00173"></a><span class="lineno">  173</span>&#160;    <span class="keyword">def </span>pycatch(exctype, f, *args):</div>
<div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;        <span class="keywordflow">try</span>:</div>
<div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;            f(*args)</div>
<div class="line"><a name="l00176"></a><span class="lineno">  176</span>&#160;        <span class="keywordflow">except</span> m.MyException <span class="keyword">as</span> e:</div>
<div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;            <a class="code" href="pybind11_8h.html#a62bcafa97abdcadb6520a62e52331b89">print</a>(e)</div>
<div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160; </div>
<div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;    <span class="comment"># C++ -&gt; Python -&gt; C++ -&gt; Python</span></div>
<div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;    <span class="keyword">with</span> capture:</div>
<div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160;        m.try_catch(</div>
<div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;            m.MyException5,</div>
<div class="line"><a name="l00183"></a><span class="lineno">  183</span>&#160;            pycatch,</div>
<div class="line"><a name="l00184"></a><span class="lineno">  184</span>&#160;            m.MyException,</div>
<div class="line"><a name="l00185"></a><span class="lineno">  185</span>&#160;            m.try_catch,</div>
<div class="line"><a name="l00186"></a><span class="lineno">  186</span>&#160;            m.MyException,</div>
<div class="line"><a name="l00187"></a><span class="lineno">  187</span>&#160;            throw_myex5,</div>
<div class="line"><a name="l00188"></a><span class="lineno">  188</span>&#160;        )</div>
<div class="line"><a name="l00189"></a><span class="lineno">  189</span>&#160;    <span class="keyword">assert</span> <a class="code" href="classstr.html">str</a>(capture).startswith(<span class="stringliteral">&quot;MyException5: nested error 5&quot;</span>)</div>
<div class="line"><a name="l00190"></a><span class="lineno">  190</span>&#160; </div>
<div class="line"><a name="l00191"></a><span class="lineno">  191</span>&#160;    <span class="comment"># C++ -&gt; Python -&gt; C++</span></div>
<div class="line"><a name="l00192"></a><span class="lineno">  192</span>&#160;    <span class="keyword">with</span> capture:</div>
<div class="line"><a name="l00193"></a><span class="lineno">  193</span>&#160;        m.try_catch(m.MyException, pycatch, m.MyException5, m.throws4)</div>
<div class="line"><a name="l00194"></a><span class="lineno">  194</span>&#160;    <span class="keyword">assert</span> capture == <span class="stringliteral">&quot;this error is rethrown&quot;</span></div>
<div class="line"><a name="l00195"></a><span class="lineno">  195</span>&#160; </div>
<div class="line"><a name="l00196"></a><span class="lineno">  196</span>&#160;    <span class="comment"># Python -&gt; C++ -&gt; Python -&gt; C++</span></div>
<div class="line"><a name="l00197"></a><span class="lineno">  197</span>&#160;    <span class="keyword">with</span> pytest.raises(m.MyException5) <span class="keyword">as</span> excinfo:</div>
<div class="line"><a name="l00198"></a><span class="lineno">  198</span>&#160;        m.try_catch(m.MyException, pycatch, m.MyException, m.throws5)</div>
<div class="line"><a name="l00199"></a><span class="lineno">  199</span>&#160;    <span class="keyword">assert</span> <a class="code" href="classstr.html">str</a>(excinfo.value) == <span class="stringliteral">&quot;this is a helper-defined translated exception&quot;</span></div>
<div class="line"><a name="l00200"></a><span class="lineno">  200</span>&#160; </div>
<div class="line"><a name="l00201"></a><span class="lineno">  201</span>&#160; </div>
<div class="line"><a name="l00202"></a><span class="lineno">  202</span>&#160;<span class="comment"># This can often happen if you wrap a pybind11 class in a Python wrapper</span></div>
<div class="line"><a name="l00203"></a><span class="lineno"><a class="line" href="namespacetest__exceptions.html#a78e93d121102ca051650c40d5de0951b">  203</a></span>&#160;<span class="keyword">def </span><a class="code" href="namespacetest__exceptions.html#a78e93d121102ca051650c40d5de0951b">test_invalid_repr</a>():</div>
<div class="line"><a name="l00204"></a><span class="lineno">  204</span>&#160;    <span class="keyword">class </span>MyRepr(<a class="code" href="classobject.html">object</a>):</div>
<div class="line"><a name="l00205"></a><span class="lineno">  205</span>&#160;        <span class="keyword">def </span>__repr__(self):</div>
<div class="line"><a name="l00206"></a><span class="lineno">  206</span>&#160;            <span class="keywordflow">raise</span> AttributeError(<span class="stringliteral">&quot;Example error&quot;</span>)</div>
<div class="line"><a name="l00207"></a><span class="lineno">  207</span>&#160; </div>
<div class="line"><a name="l00208"></a><span class="lineno">  208</span>&#160;    <span class="keyword">with</span> pytest.raises(TypeError):</div>
<div class="line"><a name="l00209"></a><span class="lineno">  209</span>&#160;        m.simple_bool_passthrough(MyRepr())</div>
</div><!-- fragment --></div><!-- contents -->
<div class="ttc" id="anamespacetest__exceptions_html_a8003f21452ee6d48d5a28cb47ae16bde"><div class="ttname"><a href="namespacetest__exceptions.html#a8003f21452ee6d48d5a28cb47ae16bde">test_exceptions.test_std_exception</a></div><div class="ttdeci">def test_std_exception(msg)</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8py_source.html#l00010">test_exceptions.py:10</a></div></div>
<div class="ttc" id="anamespacetest__exceptions_html_ae7f47864f406f18ce07b0ac482ed3054"><div class="ttname"><a href="namespacetest__exceptions.html#ae7f47864f406f18ce07b0ac482ed3054">test_exceptions.test_cross_module_exceptions</a></div><div class="ttdeci">def test_cross_module_exceptions()</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8py_source.html#l00026">test_exceptions.py:26</a></div></div>
<div class="ttc" id="anamespacetest__exceptions_html_a9ea2bf30538c97fd3968669627212988"><div class="ttname"><a href="namespacetest__exceptions.html#a9ea2bf30538c97fd3968669627212988">test_exceptions.test_error_already_set</a></div><div class="ttdeci">def test_error_already_set(msg)</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8py_source.html#l00016">test_exceptions.py:16</a></div></div>
<div class="ttc" id="agroup__python__builtins_html_gacc0a69f008d341c07ff939e0580c5985"><div class="ttname"><a href="group__python__builtins.html#gacc0a69f008d341c07ff939e0580c5985">hasattr</a></div><div class="ttdeci">bool hasattr(handle obj, handle name)</div><div class="ttdef"><b>Definition:</b> <a href="pytypes_8h_source.html#l00405">pytypes.h:405</a></div></div>
<div class="ttc" id="anamespacetest__exceptions_html_a8f1f30a6d37825f9f9b2d48b17c401e1"><div class="ttname"><a href="namespacetest__exceptions.html#a8f1f30a6d37825f9f9b2d48b17c401e1">test_exceptions.test_nested_throws</a></div><div class="ttdeci">def test_nested_throws(capture)</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8py_source.html#l00152">test_exceptions.py:152</a></div></div>
<div class="ttc" id="aclassobject_html"><div class="ttname"><a href="classobject.html">object</a></div><div class="ttdef"><b>Definition:</b> <a href="pytypes_8h_source.html#l00232">pytypes.h:232</a></div></div>
<div class="ttc" id="agroup__python__builtins_html_gade020f155a1f133cc9e245bac2981280"><div class="ttname"><a href="group__python__builtins.html#gade020f155a1f133cc9e245bac2981280">isinstance</a></div><div class="ttdeci">bool isinstance(handle obj)</div><div class="ttdef"><b>Definition:</b> <a href="pytypes_8h_source.html#l00386">pytypes.h:386</a></div></div>
<div class="ttc" id="anamespacetest__exceptions_html_ae6a0bbcfa4d024fd8de0e89bc1bae224"><div class="ttname"><a href="namespacetest__exceptions.html#ae6a0bbcfa4d024fd8de0e89bc1bae224">test_exceptions.test_python_call_in_catch</a></div><div class="ttdeci">def test_python_call_in_catch()</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8py_source.html#l00047">test_exceptions.py:47</a></div></div>
<div class="ttc" id="anamespacesetup_html_a52ffe830bc77e7f3621f33f969b6bfee"><div class="ttname"><a href="namespacesetup.html#a52ffe830bc77e7f3621f33f969b6bfee">setup.msg</a></div><div class="ttdeci">string msg</div><div class="ttdef"><b>Definition:</b> <a href="setup_8py_source.html#l00047">setup.py:47</a></div></div>
<div class="ttc" id="anamespacetest__exceptions_html_a4e0d71245eded53a1785ca21662e6143"><div class="ttname"><a href="namespacetest__exceptions.html#a4e0d71245eded53a1785ca21662e6143">test_exceptions.test_exception_matches</a></div><div class="ttdeci">def test_exception_matches()</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8py_source.html#l00091">test_exceptions.py:91</a></div></div>
<div class="ttc" id="anamespacetest__exceptions_html_a2e0d2d2cf645e4c73e4926700aba5788"><div class="ttname"><a href="namespacetest__exceptions.html#a2e0d2d2cf645e4c73e4926700aba5788">test_exceptions.test_python_alreadyset_in_destructor</a></div><div class="ttdeci">def test_python_alreadyset_in_destructor(monkeypatch, capsys)</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8py_source.html#l00063">test_exceptions.py:63</a></div></div>
<div class="ttc" id="anamespacetest__exceptions_html_ac7bc0c3050aa0ae201e0800f4bec21f2"><div class="ttname"><a href="namespacetest__exceptions.html#ac7bc0c3050aa0ae201e0800f4bec21f2">test_exceptions.ignore_pytest_unraisable_warning</a></div><div class="ttdeci">def ignore_pytest_unraisable_warning(f)</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8py_source.html#l00053">test_exceptions.py:53</a></div></div>
<div class="ttc" id="aclassstr_html"><div class="ttname"><a href="classstr.html">str</a></div><div class="ttdef"><b>Definition:</b> <a href="pytypes_8h_source.html#l00946">pytypes.h:946</a></div></div>
<div class="ttc" id="anamespacetest__exceptions_html_a78e93d121102ca051650c40d5de0951b"><div class="ttname"><a href="namespacetest__exceptions.html#a78e93d121102ca051650c40d5de0951b">test_exceptions.test_invalid_repr</a></div><div class="ttdeci">def test_invalid_repr()</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8py_source.html#l00203">test_exceptions.py:203</a></div></div>
<div class="ttc" id="anamespacetest__exceptions_html_a1e734955761fef2aecda8f88fb97d0c6"><div class="ttname"><a href="namespacetest__exceptions.html#a1e734955761fef2aecda8f88fb97d0c6">test_exceptions.test_custom</a></div><div class="ttdeci">def test_custom(msg)</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8py_source.html#l00097">test_exceptions.py:97</a></div></div>
<div class="ttc" id="apybind11_8h_html_a62bcafa97abdcadb6520a62e52331b89"><div class="ttname"><a href="pybind11_8h.html#a62bcafa97abdcadb6520a62e52331b89">print</a></div><div class="ttdeci">PYBIND11_NOINLINE void print(tuple args, dict kwargs)</div><div class="ttdef"><b>Definition:</b> <a href="pybind11_8h_source.html#l02056">pybind11.h:2056</a></div></div>
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by &#160;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/>
</a> 1.8.19
</small></address>
</body>
</html>
