<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.19"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>cppyabm: /Users/matin/Downloads/testProjs/CppyABM/examples/Cppy/build/_deps/pybind11-src/tests/test_exceptions.cpp Source File</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
  $(document).ready(function() { init_search(); });
/* @license-end */
</script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">cppyabm
   &#160;<span id="projectnumber">1.0.17</span>
   </div>
   <div id="projectbrief">An agent-based library to integrate C++ and Python</div>
  </td>
   <td>        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="search/mag_sel.png"
               onmouseover="return searchBox.OnSearchSelectShow()"
               onmouseout="return searchBox.OnSearchSelectHide()"
               alt=""/>
          <input type="text" id="MSearchField" value="Search" accesskey="S"
               onfocus="searchBox.OnSearchFieldFocus(true)" 
               onblur="searchBox.OnSearchFieldFocus(false)" 
               onkeyup="searchBox.OnSearchFieldChange(event)"/>
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="search/close.png" alt=""/></a>
          </span>
        </div>
</td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.19 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search');
/* @license-end */
</script>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_d28a4824dc47e487b107a5db32ef43c4.html">examples</a></li><li class="navelem"><a class="el" href="dir_6e786e66b74cc92d0e12ff5289cc6076.html">Cppy</a></li><li class="navelem"><a class="el" href="dir_ea8d043fc2589865e6ec2e5542984e72.html">build</a></li><li class="navelem"><a class="el" href="dir_535defd9c8def468f374af6a35b22bd0.html">_deps</a></li><li class="navelem"><a class="el" href="dir_9c141c3fefe21646e8634f2c1936b02d.html">pybind11-src</a></li><li class="navelem"><a class="el" href="dir_d8b2a6794d24dbb42d578bb674b1906e.html">tests</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">test_exceptions.cpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="test__exceptions_8cpp.html">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;<span class="comment">/*</span></div>
<div class="line"><a name="l00002"></a><span class="lineno">    2</span>&#160;<span class="comment">    tests/test_custom-exceptions.cpp -- exception translation</span></div>
<div class="line"><a name="l00003"></a><span class="lineno">    3</span>&#160;<span class="comment"></span> </div>
<div class="line"><a name="l00004"></a><span class="lineno">    4</span>&#160;<span class="comment">    Copyright (c) 2016 Pim Schellart &lt;P.Schellart@princeton.edu&gt;</span></div>
<div class="line"><a name="l00005"></a><span class="lineno">    5</span>&#160;<span class="comment"></span> </div>
<div class="line"><a name="l00006"></a><span class="lineno">    6</span>&#160;<span class="comment">    All rights reserved. Use of this source code is governed by a</span></div>
<div class="line"><a name="l00007"></a><span class="lineno">    7</span>&#160;<span class="comment">    BSD-style license that can be found in the LICENSE file.</span></div>
<div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;<span class="comment">*/</span></div>
<div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160; </div>
<div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="pybind11__tests_8h.html">pybind11_tests.h</a>&quot;</span></div>
<div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160; </div>
<div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="comment">// A type that should be raised as an exception in Python</span></div>
<div class="line"><a name="l00013"></a><span class="lineno"><a class="line" href="class_my_exception.html">   13</a></span>&#160;<span class="keyword">class </span><a class="code" href="class_my_exception.html">MyException</a> : <span class="keyword">public</span> std::exception {</div>
<div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="keyword">public</span>:</div>
<div class="line"><a name="l00015"></a><span class="lineno"><a class="line" href="class_my_exception.html#abfe694fd781fe4301432e27e7dcfa249">   15</a></span>&#160;    <span class="keyword">explicit</span> <a class="code" href="class_my_exception.html#abfe694fd781fe4301432e27e7dcfa249">MyException</a>(<span class="keyword">const</span> <span class="keywordtype">char</span> * <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>) : message{<a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>} {}</div>
<div class="line"><a name="l00016"></a><span class="lineno"><a class="line" href="class_my_exception.html#ad889306542c787a984839153b9e8462f">   16</a></span>&#160;    <span class="keyword">const</span> <span class="keywordtype">char</span> * <a class="code" href="class_my_exception.html#ad889306542c787a984839153b9e8462f">what</a>() const noexcept<span class="keyword"> override </span>{<span class="keywordflow">return</span> message.c_str();}</div>
<div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="keyword">private</span>:</div>
<div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;    std::string message = <span class="stringliteral">&quot;&quot;</span>;</div>
<div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;};</div>
<div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160; </div>
<div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;<span class="comment">// A type that should be translated to a standard Python exception</span></div>
<div class="line"><a name="l00022"></a><span class="lineno"><a class="line" href="class_my_exception2.html">   22</a></span>&#160;<span class="keyword">class </span><a class="code" href="class_my_exception2.html">MyException2</a> : <span class="keyword">public</span> std::exception {</div>
<div class="line"><a name="l00023"></a><span class="lineno">   23</span>&#160;<span class="keyword">public</span>:</div>
<div class="line"><a name="l00024"></a><span class="lineno"><a class="line" href="class_my_exception2.html#aaf4559b3dfb7b8d164708d92c3c57730">   24</a></span>&#160;    <span class="keyword">explicit</span> <a class="code" href="class_my_exception2.html#aaf4559b3dfb7b8d164708d92c3c57730">MyException2</a>(<span class="keyword">const</span> <span class="keywordtype">char</span> * <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>) : message{<a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>} {}</div>
<div class="line"><a name="l00025"></a><span class="lineno"><a class="line" href="class_my_exception2.html#a6e566f7a585007a1f6f6b009acfc696c">   25</a></span>&#160;    <span class="keyword">const</span> <span class="keywordtype">char</span> * <a class="code" href="class_my_exception2.html#a6e566f7a585007a1f6f6b009acfc696c">what</a>() const noexcept<span class="keyword"> override </span>{<span class="keywordflow">return</span> message.c_str();}</div>
<div class="line"><a name="l00026"></a><span class="lineno">   26</span>&#160;<span class="keyword">private</span>:</div>
<div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;    std::string message = <span class="stringliteral">&quot;&quot;</span>;</div>
<div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;};</div>
<div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160; </div>
<div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;<span class="comment">// A type that is not derived from std::exception (and is thus unknown)</span></div>
<div class="line"><a name="l00031"></a><span class="lineno"><a class="line" href="class_my_exception3.html">   31</a></span>&#160;<span class="keyword">class </span><a class="code" href="class_my_exception3.html">MyException3</a> {</div>
<div class="line"><a name="l00032"></a><span class="lineno">   32</span>&#160;<span class="keyword">public</span>:</div>
<div class="line"><a name="l00033"></a><span class="lineno"><a class="line" href="class_my_exception3.html#a5927c6264e4814f9fe092b0c33e054a1">   33</a></span>&#160;    <span class="keyword">explicit</span> <a class="code" href="class_my_exception3.html#a5927c6264e4814f9fe092b0c33e054a1">MyException3</a>(<span class="keyword">const</span> <span class="keywordtype">char</span> * <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>) : message{<a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>} {}</div>
<div class="line"><a name="l00034"></a><span class="lineno"><a class="line" href="class_my_exception3.html#a7f94bec36360fef4942847e6859f6f05">   34</a></span>&#160;    <span class="keyword">virtual</span> <span class="keyword">const</span> <span class="keywordtype">char</span> * <a class="code" href="class_my_exception3.html#a7f94bec36360fef4942847e6859f6f05">what</a>() const noexcept {<span class="keywordflow">return</span> message.c_str();}</div>
<div class="line"><a name="l00035"></a><span class="lineno">   35</span>&#160;    <span class="comment">// Rule of 5 BEGIN: to preempt compiler warnings.</span></div>
<div class="line"><a name="l00036"></a><span class="lineno"><a class="line" href="class_my_exception3.html#a7cf3fa1a11667d918a3ffd75ec484805">   36</a></span>&#160;    <a class="code" href="class_my_exception3.html#a7cf3fa1a11667d918a3ffd75ec484805">MyException3</a>(<span class="keyword">const</span> <a class="code" href="class_my_exception3.html">MyException3</a>&amp;) = <span class="keywordflow">default</span>;</div>
<div class="line"><a name="l00037"></a><span class="lineno"><a class="line" href="class_my_exception3.html#aaa5389018cace55ea0c5b89c4f2c15f8">   37</a></span>&#160;    <a class="code" href="class_my_exception3.html#aaa5389018cace55ea0c5b89c4f2c15f8">MyException3</a>(<a class="code" href="class_my_exception3.html">MyException3</a>&amp;&amp;) = <span class="keywordflow">default</span>;</div>
<div class="line"><a name="l00038"></a><span class="lineno"><a class="line" href="class_my_exception3.html#a5a38e76944b26f7cba26d13384502649">   38</a></span>&#160;    <a class="code" href="class_my_exception3.html">MyException3</a>&amp; <a class="code" href="class_my_exception3.html#a5a38e76944b26f7cba26d13384502649">operator=</a>(<span class="keyword">const</span> <a class="code" href="class_my_exception3.html">MyException3</a>&amp;) = <span class="keywordflow">default</span>;</div>
<div class="line"><a name="l00039"></a><span class="lineno"><a class="line" href="class_my_exception3.html#a862afaec6b831a6298f6c1e500423aac">   39</a></span>&#160;    <a class="code" href="class_my_exception3.html">MyException3</a>&amp; <a class="code" href="class_my_exception3.html#a862afaec6b831a6298f6c1e500423aac">operator=</a>(<a class="code" href="class_my_exception3.html">MyException3</a>&amp;&amp;) = <span class="keywordflow">default</span>;</div>
<div class="line"><a name="l00040"></a><span class="lineno"><a class="line" href="class_my_exception3.html#a56081da37152bc94294300508d9943d3">   40</a></span>&#160;    <span class="keyword">virtual</span> <a class="code" href="class_my_exception3.html#a56081da37152bc94294300508d9943d3">~MyException3</a>() = <span class="keywordflow">default</span>;</div>
<div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;    <span class="comment">// Rule of 5 END.</span></div>
<div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;<span class="keyword">private</span>:</div>
<div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;    std::string message = <span class="stringliteral">&quot;&quot;</span>;</div>
<div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;};</div>
<div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160; </div>
<div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;<span class="comment">// A type that should be translated to MyException</span></div>
<div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;<span class="comment">// and delegated to its exception translator</span></div>
<div class="line"><a name="l00048"></a><span class="lineno"><a class="line" href="class_my_exception4.html">   48</a></span>&#160;<span class="keyword">class </span><a class="code" href="class_my_exception4.html">MyException4</a> : <span class="keyword">public</span> std::exception {</div>
<div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;<span class="keyword">public</span>:</div>
<div class="line"><a name="l00050"></a><span class="lineno"><a class="line" href="class_my_exception4.html#a7c1361aa20152bdba906a5d029ee1f19">   50</a></span>&#160;    <span class="keyword">explicit</span> <a class="code" href="class_my_exception4.html#a7c1361aa20152bdba906a5d029ee1f19">MyException4</a>(<span class="keyword">const</span> <span class="keywordtype">char</span> * <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>) : message{<a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>} {}</div>
<div class="line"><a name="l00051"></a><span class="lineno"><a class="line" href="class_my_exception4.html#a92d0b8dac77b24447648c218f01d58ae">   51</a></span>&#160;    <span class="keyword">const</span> <span class="keywordtype">char</span> * <a class="code" href="class_my_exception4.html#a92d0b8dac77b24447648c218f01d58ae">what</a>() const noexcept<span class="keyword"> override </span>{<span class="keywordflow">return</span> message.c_str();}</div>
<div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;<span class="keyword">private</span>:</div>
<div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;    std::string message = <span class="stringliteral">&quot;&quot;</span>;</div>
<div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;};</div>
<div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160; </div>
<div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160; </div>
<div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;<span class="comment">// Like the above, but declared via the helper function</span></div>
<div class="line"><a name="l00058"></a><span class="lineno"><a class="line" href="class_my_exception5.html">   58</a></span>&#160;<span class="keyword">class </span><a class="code" href="class_my_exception5.html">MyException5</a> : <span class="keyword">public</span> std::logic_error {</div>
<div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;<span class="keyword">public</span>:</div>
<div class="line"><a name="l00060"></a><span class="lineno"><a class="line" href="class_my_exception5.html#a10ef0850e42ccce182bbc1e9021f5369">   60</a></span>&#160;    <span class="keyword">explicit</span> <a class="code" href="class_my_exception5.html#a10ef0850e42ccce182bbc1e9021f5369">MyException5</a>(<span class="keyword">const</span> std::string &amp;what) : std::logic_error(what) {}</div>
<div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;};</div>
<div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160; </div>
<div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;<span class="comment">// Inherits from MyException5</span></div>
<div class="line"><a name="l00064"></a><span class="lineno"><a class="line" href="class_my_exception5__1.html">   64</a></span>&#160;<span class="keyword">class </span><a class="code" href="class_my_exception5__1.html">MyException5_1</a> : <span class="keyword">public</span> <a class="code" href="class_my_exception5.html">MyException5</a> {</div>
<div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;    <span class="keyword">using</span> <a class="code" href="class_my_exception5.html#a10ef0850e42ccce182bbc1e9021f5369">MyException5::MyException5</a>;</div>
<div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;};</div>
<div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160; </div>
<div class="line"><a name="l00068"></a><span class="lineno"><a class="line" href="struct_python_call_in_destructor.html">   68</a></span>&#160;<span class="keyword">struct </span><a class="code" href="struct_python_call_in_destructor.html">PythonCallInDestructor</a> {</div>
<div class="line"><a name="l00069"></a><span class="lineno"><a class="line" href="struct_python_call_in_destructor.html#a3bd241ae5d0c2432978dd95c10f8c908">   69</a></span>&#160;    <a class="code" href="struct_python_call_in_destructor.html#a3bd241ae5d0c2432978dd95c10f8c908">PythonCallInDestructor</a>(<span class="keyword">const</span> py::dict &amp;<a class="code" href="struct_python_call_in_destructor.html#a31f3a6f3e208e088742f96db98bbb553">d</a>) : <a class="code" href="struct_python_call_in_destructor.html#a31f3a6f3e208e088742f96db98bbb553">d</a>(<a class="code" href="struct_python_call_in_destructor.html#a31f3a6f3e208e088742f96db98bbb553">d</a>) {}</div>
<div class="line"><a name="l00070"></a><span class="lineno"><a class="line" href="struct_python_call_in_destructor.html#a11090c7ca44f6e43bad3a03412c82dbd">   70</a></span>&#160;    <a class="code" href="struct_python_call_in_destructor.html#a11090c7ca44f6e43bad3a03412c82dbd">~PythonCallInDestructor</a>() { <a class="code" href="struct_python_call_in_destructor.html#a31f3a6f3e208e088742f96db98bbb553">d</a>[<span class="stringliteral">&quot;good&quot;</span>] = <span class="keyword">true</span>; }</div>
<div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160; </div>
<div class="line"><a name="l00072"></a><span class="lineno"><a class="line" href="struct_python_call_in_destructor.html#a31f3a6f3e208e088742f96db98bbb553">   72</a></span>&#160;    py::dict <a class="code" href="struct_python_call_in_destructor.html#a31f3a6f3e208e088742f96db98bbb553">d</a>;</div>
<div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;};</div>
<div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160; </div>
<div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160; </div>
<div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160; </div>
<div class="line"><a name="l00077"></a><span class="lineno"><a class="line" href="struct_python_already_set_in_destructor.html">   77</a></span>&#160;<span class="keyword">struct </span><a class="code" href="struct_python_already_set_in_destructor.html">PythonAlreadySetInDestructor</a> {</div>
<div class="line"><a name="l00078"></a><span class="lineno"><a class="line" href="struct_python_already_set_in_destructor.html#ae0b6a18a28340298ba02754e21225fe8">   78</a></span>&#160;    <a class="code" href="struct_python_already_set_in_destructor.html#ae0b6a18a28340298ba02754e21225fe8">PythonAlreadySetInDestructor</a>(<span class="keyword">const</span> py::str &amp;<a class="code" href="struct_python_already_set_in_destructor.html#a020fc31e0ab99d1662aaf93e5ffacf88">s</a>) : <a class="code" href="struct_python_already_set_in_destructor.html#a020fc31e0ab99d1662aaf93e5ffacf88">s</a>(<a class="code" href="struct_python_already_set_in_destructor.html#a020fc31e0ab99d1662aaf93e5ffacf88">s</a>) {}</div>
<div class="line"><a name="l00079"></a><span class="lineno"><a class="line" href="struct_python_already_set_in_destructor.html#a2d863c983b4f0b3d5857e23203fd42dc">   79</a></span>&#160;    <a class="code" href="struct_python_already_set_in_destructor.html#a2d863c983b4f0b3d5857e23203fd42dc">~PythonAlreadySetInDestructor</a>() {</div>
<div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;        py::dict foo;</div>
<div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;        <span class="keywordflow">try</span> {</div>
<div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;            <span class="comment">// Assign to a py::object to force read access of nonexistent dict entry</span></div>
<div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;            py::object o = foo[<span class="stringliteral">&quot;bar&quot;</span>];</div>
<div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;        }</div>
<div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;        <span class="keywordflow">catch</span> (py::error_already_set&amp; ex) {</div>
<div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;            ex.discard_as_unraisable(<a class="code" href="struct_python_already_set_in_destructor.html#a020fc31e0ab99d1662aaf93e5ffacf88">s</a>);</div>
<div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;        }</div>
<div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;    }</div>
<div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160; </div>
<div class="line"><a name="l00090"></a><span class="lineno"><a class="line" href="struct_python_already_set_in_destructor.html#a020fc31e0ab99d1662aaf93e5ffacf88">   90</a></span>&#160;    py::str <a class="code" href="struct_python_already_set_in_destructor.html#a020fc31e0ab99d1662aaf93e5ffacf88">s</a>;</div>
<div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;};</div>
<div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160; </div>
<div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160; </div>
<div class="line"><a name="l00094"></a><span class="lineno"><a class="line" href="test__exceptions_8cpp.html#a2f500ba7c1af71bd5a5ff919bfa99632">   94</a></span>&#160;<a class="code" href="test__exceptions_8cpp.html#a2f500ba7c1af71bd5a5ff919bfa99632">TEST_SUBMODULE</a>(exceptions, <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>) {</div>
<div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;throw_std_exception&quot;</span>, []() {</div>
<div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;        <span class="keywordflow">throw</span> std::runtime_error(<span class="stringliteral">&quot;This exception was intentionally thrown.&quot;</span>);</div>
<div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;    });</div>
<div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160; </div>
<div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;    <span class="comment">// make a new custom exception and use it as a translation target</span></div>
<div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;    <span class="keyword">static</span> py::exception&lt;MyException&gt; ex(<a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>, <span class="stringliteral">&quot;MyException&quot;</span>);</div>
<div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;    <a class="code" href="pybind11_8h.html#a0a77063d21919c13ddfeb8caf29eef59">py::register_exception_translator</a>([](std::exception_ptr p) {</div>
<div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;        <span class="keywordflow">try</span> {</div>
<div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;            <span class="keywordflow">if</span> (p) std::rethrow_exception(p);</div>
<div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;        } <span class="keywordflow">catch</span> (<span class="keyword">const</span> <a class="code" href="class_my_exception.html">MyException</a> &amp;e) {</div>
<div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;            <span class="comment">// Set MyException as the active python error</span></div>
<div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;            ex(e.<a class="code" href="class_my_exception.html#ad889306542c787a984839153b9e8462f">what</a>());</div>
<div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;        }</div>
<div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;    });</div>
<div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160; </div>
<div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;    <span class="comment">// register new translator for MyException2</span></div>
<div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;    <span class="comment">// no need to store anything here because this type will</span></div>
<div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;    <span class="comment">// never by visible from Python</span></div>
<div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;    <a class="code" href="pybind11_8h.html#a0a77063d21919c13ddfeb8caf29eef59">py::register_exception_translator</a>([](std::exception_ptr p) {</div>
<div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;        <span class="keywordflow">try</span> {</div>
<div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;            <span class="keywordflow">if</span> (p) std::rethrow_exception(p);</div>
<div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;        } <span class="keywordflow">catch</span> (<span class="keyword">const</span> <a class="code" href="class_my_exception2.html">MyException2</a> &amp;e) {</div>
<div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;            <span class="comment">// Translate this exception to a standard RuntimeError</span></div>
<div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;            PyErr_SetString(PyExc_RuntimeError, e.<a class="code" href="class_my_exception2.html#a6e566f7a585007a1f6f6b009acfc696c">what</a>());</div>
<div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;        }</div>
<div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;    });</div>
<div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160; </div>
<div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;    <span class="comment">// register new translator for MyException4</span></div>
<div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;    <span class="comment">// which will catch it and delegate to the previously registered</span></div>
<div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;    <span class="comment">// translator for MyException by throwing a new exception</span></div>
<div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;    <a class="code" href="pybind11_8h.html#a0a77063d21919c13ddfeb8caf29eef59">py::register_exception_translator</a>([](std::exception_ptr p) {</div>
<div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;        <span class="keywordflow">try</span> {</div>
<div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;            <span class="keywordflow">if</span> (p) std::rethrow_exception(p);</div>
<div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;        } <span class="keywordflow">catch</span> (<span class="keyword">const</span> <a class="code" href="class_my_exception4.html">MyException4</a> &amp;e) {</div>
<div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;            <span class="keywordflow">throw</span> <a class="code" href="class_my_exception.html">MyException</a>(e.<a class="code" href="class_my_exception4.html#a92d0b8dac77b24447648c218f01d58ae">what</a>());</div>
<div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;        }</div>
<div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;    });</div>
<div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160; </div>
<div class="line"><a name="l00133"></a><span class="lineno">  133</span>&#160;    <span class="comment">// A simple exception translation:</span></div>
<div class="line"><a name="l00134"></a><span class="lineno">  134</span>&#160;    <span class="keyword">auto</span> ex5 = py::register_exception&lt;MyException5&gt;(<a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>, <span class="stringliteral">&quot;MyException5&quot;</span>);</div>
<div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;    <span class="comment">// A slightly more complicated one that declares MyException5_1 as a subclass of MyException5</span></div>
<div class="line"><a name="l00136"></a><span class="lineno">  136</span>&#160;    py::register_exception&lt;MyException5_1&gt;(<a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>, <span class="stringliteral">&quot;MyException5_1&quot;</span>, ex5.ptr());</div>
<div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160; </div>
<div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;throws1&quot;</span>, []() { <span class="keywordflow">throw</span> <a class="code" href="class_my_exception.html">MyException</a>(<span class="stringliteral">&quot;this error should go to a custom type&quot;</span>); });</div>
<div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;throws2&quot;</span>, []() { <span class="keywordflow">throw</span> <a class="code" href="class_my_exception2.html">MyException2</a>(<span class="stringliteral">&quot;this error should go to a standard Python exception&quot;</span>); });</div>
<div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;throws3&quot;</span>, []() { <span class="keywordflow">throw</span> <a class="code" href="class_my_exception3.html">MyException3</a>(<span class="stringliteral">&quot;this error cannot be translated&quot;</span>); });</div>
<div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;throws4&quot;</span>, []() { <span class="keywordflow">throw</span> <a class="code" href="class_my_exception4.html">MyException4</a>(<span class="stringliteral">&quot;this error is rethrown&quot;</span>); });</div>
<div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;throws5&quot;</span>, []() { <span class="keywordflow">throw</span> <a class="code" href="class_my_exception5.html">MyException5</a>(<span class="stringliteral">&quot;this is a helper-defined translated exception&quot;</span>); });</div>
<div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;throws5_1&quot;</span>, []() { <span class="keywordflow">throw</span> <a class="code" href="class_my_exception5__1.html">MyException5_1</a>(<span class="stringliteral">&quot;MyException5 subclass&quot;</span>); });</div>
<div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;throws_logic_error&quot;</span>, []() { <span class="keywordflow">throw</span> std::logic_error(<span class="stringliteral">&quot;this error should fall through to the standard handler&quot;</span>); });</div>
<div class="line"><a name="l00145"></a><span class="lineno">  145</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;throws_overflow_error&quot;</span>, []() {<span class="keywordflow">throw</span> std::overflow_error(<span class="stringliteral">&quot;&quot;</span>); });</div>
<div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;exception_matches&quot;</span>, []() {</div>
<div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;        py::dict foo;</div>
<div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;        <span class="keywordflow">try</span> {</div>
<div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;            <span class="comment">// Assign to a py::object to force read access of nonexistent dict entry</span></div>
<div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;            py::object o = foo[<span class="stringliteral">&quot;bar&quot;</span>];</div>
<div class="line"><a name="l00151"></a><span class="lineno">  151</span>&#160;        }</div>
<div class="line"><a name="l00152"></a><span class="lineno">  152</span>&#160;        <span class="keywordflow">catch</span> (py::error_already_set&amp; ex) {</div>
<div class="line"><a name="l00153"></a><span class="lineno">  153</span>&#160;            <span class="keywordflow">if</span> (!ex.matches(PyExc_KeyError)) <span class="keywordflow">throw</span>;</div>
<div class="line"><a name="l00154"></a><span class="lineno">  154</span>&#160;            <span class="keywordflow">return</span> <span class="keyword">true</span>;</div>
<div class="line"><a name="l00155"></a><span class="lineno">  155</span>&#160;        }</div>
<div class="line"><a name="l00156"></a><span class="lineno">  156</span>&#160;        <span class="keywordflow">return</span> <span class="keyword">false</span>;</div>
<div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;    });</div>
<div class="line"><a name="l00158"></a><span class="lineno">  158</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;exception_matches_base&quot;</span>, []() {</div>
<div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;        py::dict foo;</div>
<div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;        <span class="keywordflow">try</span> {</div>
<div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;            <span class="comment">// Assign to a py::object to force read access of nonexistent dict entry</span></div>
<div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;            py::object o = foo[<span class="stringliteral">&quot;bar&quot;</span>];</div>
<div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160;        }</div>
<div class="line"><a name="l00164"></a><span class="lineno">  164</span>&#160;        <span class="keywordflow">catch</span> (py::error_already_set &amp;ex) {</div>
<div class="line"><a name="l00165"></a><span class="lineno">  165</span>&#160;            <span class="keywordflow">if</span> (!ex.matches(PyExc_Exception)) <span class="keywordflow">throw</span>;</div>
<div class="line"><a name="l00166"></a><span class="lineno">  166</span>&#160;            <span class="keywordflow">return</span> <span class="keyword">true</span>;</div>
<div class="line"><a name="l00167"></a><span class="lineno">  167</span>&#160;        }</div>
<div class="line"><a name="l00168"></a><span class="lineno">  168</span>&#160;        <span class="keywordflow">return</span> <span class="keyword">false</span>;</div>
<div class="line"><a name="l00169"></a><span class="lineno">  169</span>&#160;    });</div>
<div class="line"><a name="l00170"></a><span class="lineno">  170</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;modulenotfound_exception_matches_base&quot;</span>, []() {</div>
<div class="line"><a name="l00171"></a><span class="lineno">  171</span>&#160;        <span class="keywordflow">try</span> {</div>
<div class="line"><a name="l00172"></a><span class="lineno">  172</span>&#160;            <span class="comment">// On Python &gt;= 3.6, this raises a ModuleNotFoundError, a subclass of ImportError</span></div>
<div class="line"><a name="l00173"></a><span class="lineno">  173</span>&#160;            py::module_::import(<span class="stringliteral">&quot;nonexistent&quot;</span>);</div>
<div class="line"><a name="l00174"></a><span class="lineno">  174</span>&#160;        }</div>
<div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;        <span class="keywordflow">catch</span> (py::error_already_set &amp;ex) {</div>
<div class="line"><a name="l00176"></a><span class="lineno">  176</span>&#160;            <span class="keywordflow">if</span> (!ex.matches(PyExc_ImportError)) <span class="keywordflow">throw</span>;</div>
<div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;            <span class="keywordflow">return</span> <span class="keyword">true</span>;</div>
<div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;        }</div>
<div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;        <span class="keywordflow">return</span> <span class="keyword">false</span>;</div>
<div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160;    });</div>
<div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160; </div>
<div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;throw_already_set&quot;</span>, [](<span class="keywordtype">bool</span> err) {</div>
<div class="line"><a name="l00183"></a><span class="lineno">  183</span>&#160;        <span class="keywordflow">if</span> (err)</div>
<div class="line"><a name="l00184"></a><span class="lineno">  184</span>&#160;            PyErr_SetString(PyExc_ValueError, <span class="stringliteral">&quot;foo&quot;</span>);</div>
<div class="line"><a name="l00185"></a><span class="lineno">  185</span>&#160;        <span class="keywordflow">try</span> {</div>
<div class="line"><a name="l00186"></a><span class="lineno">  186</span>&#160;            <span class="keywordflow">throw</span> py::error_already_set();</div>
<div class="line"><a name="l00187"></a><span class="lineno">  187</span>&#160;        } <span class="keywordflow">catch</span> (<span class="keyword">const</span> std::runtime_error&amp; e) {</div>
<div class="line"><a name="l00188"></a><span class="lineno">  188</span>&#160;            <span class="keywordflow">if</span> ((err &amp;&amp; e.what() != std::string(<span class="stringliteral">&quot;ValueError: foo&quot;</span>)) ||</div>
<div class="line"><a name="l00189"></a><span class="lineno">  189</span>&#160;                (!err &amp;&amp; e.what() != std::string(<span class="stringliteral">&quot;Unknown internal error occurred&quot;</span>)))</div>
<div class="line"><a name="l00190"></a><span class="lineno">  190</span>&#160;            {</div>
<div class="line"><a name="l00191"></a><span class="lineno">  191</span>&#160;                PyErr_Clear();</div>
<div class="line"><a name="l00192"></a><span class="lineno">  192</span>&#160;                <span class="keywordflow">throw</span> std::runtime_error(<span class="stringliteral">&quot;error message mismatch&quot;</span>);</div>
<div class="line"><a name="l00193"></a><span class="lineno">  193</span>&#160;            }</div>
<div class="line"><a name="l00194"></a><span class="lineno">  194</span>&#160;        }</div>
<div class="line"><a name="l00195"></a><span class="lineno">  195</span>&#160;        PyErr_Clear();</div>
<div class="line"><a name="l00196"></a><span class="lineno">  196</span>&#160;        <span class="keywordflow">if</span> (err)</div>
<div class="line"><a name="l00197"></a><span class="lineno">  197</span>&#160;            PyErr_SetString(PyExc_ValueError, <span class="stringliteral">&quot;foo&quot;</span>);</div>
<div class="line"><a name="l00198"></a><span class="lineno">  198</span>&#160;        <span class="keywordflow">throw</span> py::error_already_set();</div>
<div class="line"><a name="l00199"></a><span class="lineno">  199</span>&#160;    });</div>
<div class="line"><a name="l00200"></a><span class="lineno">  200</span>&#160; </div>
<div class="line"><a name="l00201"></a><span class="lineno">  201</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;python_call_in_destructor&quot;</span>, [](py::dict d) {</div>
<div class="line"><a name="l00202"></a><span class="lineno">  202</span>&#160;        <span class="keywordflow">try</span> {</div>
<div class="line"><a name="l00203"></a><span class="lineno">  203</span>&#160;            <a class="code" href="struct_python_call_in_destructor.html">PythonCallInDestructor</a> set_dict_in_destructor(d);</div>
<div class="line"><a name="l00204"></a><span class="lineno">  204</span>&#160;            PyErr_SetString(PyExc_ValueError, <span class="stringliteral">&quot;foo&quot;</span>);</div>
<div class="line"><a name="l00205"></a><span class="lineno">  205</span>&#160;            <span class="keywordflow">throw</span> py::error_already_set();</div>
<div class="line"><a name="l00206"></a><span class="lineno">  206</span>&#160;        } <span class="keywordflow">catch</span> (<span class="keyword">const</span> py::error_already_set&amp;) {</div>
<div class="line"><a name="l00207"></a><span class="lineno">  207</span>&#160;            <span class="keywordflow">return</span> <span class="keyword">true</span>;</div>
<div class="line"><a name="l00208"></a><span class="lineno">  208</span>&#160;        }</div>
<div class="line"><a name="l00209"></a><span class="lineno">  209</span>&#160;        <span class="keywordflow">return</span> <span class="keyword">false</span>;</div>
<div class="line"><a name="l00210"></a><span class="lineno">  210</span>&#160;    });</div>
<div class="line"><a name="l00211"></a><span class="lineno">  211</span>&#160; </div>
<div class="line"><a name="l00212"></a><span class="lineno">  212</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;python_alreadyset_in_destructor&quot;</span>, [](py::str s) {</div>
<div class="line"><a name="l00213"></a><span class="lineno">  213</span>&#160;        <a class="code" href="struct_python_already_set_in_destructor.html">PythonAlreadySetInDestructor</a> alreadyset_in_destructor(s);</div>
<div class="line"><a name="l00214"></a><span class="lineno">  214</span>&#160;        <span class="keywordflow">return</span> <span class="keyword">true</span>;</div>
<div class="line"><a name="l00215"></a><span class="lineno">  215</span>&#160;    });</div>
<div class="line"><a name="l00216"></a><span class="lineno">  216</span>&#160; </div>
<div class="line"><a name="l00217"></a><span class="lineno">  217</span>&#160;    <span class="comment">// test_nested_throws</span></div>
<div class="line"><a name="l00218"></a><span class="lineno">  218</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;try_catch&quot;</span>, [<a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>](py::object exc_type, py::function f, py::args <a class="code" href="classargs.html">args</a>) {</div>
<div class="line"><a name="l00219"></a><span class="lineno">  219</span>&#160;        <span class="keywordflow">try</span> { f(*<a class="code" href="classargs.html">args</a>); }</div>
<div class="line"><a name="l00220"></a><span class="lineno">  220</span>&#160;        <span class="keywordflow">catch</span> (py::error_already_set &amp;ex) {</div>
<div class="line"><a name="l00221"></a><span class="lineno">  221</span>&#160;            <span class="keywordflow">if</span> (ex.matches(exc_type))</div>
<div class="line"><a name="l00222"></a><span class="lineno">  222</span>&#160;                <a class="code" href="pybind11_8h.html#a62bcafa97abdcadb6520a62e52331b89">py::print</a>(ex.what());</div>
<div class="line"><a name="l00223"></a><span class="lineno">  223</span>&#160;            <span class="keywordflow">else</span></div>
<div class="line"><a name="l00224"></a><span class="lineno">  224</span>&#160;                <span class="keywordflow">throw</span>;</div>
<div class="line"><a name="l00225"></a><span class="lineno">  225</span>&#160;        }</div>
<div class="line"><a name="l00226"></a><span class="lineno">  226</span>&#160;    });</div>
<div class="line"><a name="l00227"></a><span class="lineno">  227</span>&#160; </div>
<div class="line"><a name="l00228"></a><span class="lineno">  228</span>&#160;    <span class="comment">// Test repr that cannot be displayed</span></div>
<div class="line"><a name="l00229"></a><span class="lineno">  229</span>&#160;    <a class="code" href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">m</a>.def(<span class="stringliteral">&quot;simple_bool_passthrough&quot;</span>, [](<span class="keywordtype">bool</span> <a class="code" href="namespacetest__builtin__casters.html#a60ceadcddedff98a968a458fec3a1fc1">x</a>) {<span class="keywordflow">return</span> <a class="code" href="namespacetest__builtin__casters.html#a60ceadcddedff98a968a458fec3a1fc1">x</a>;});</div>
<div class="line"><a name="l00230"></a><span class="lineno">  230</span>&#160; </div>
<div class="line"><a name="l00231"></a><span class="lineno">  231</span>&#160;}</div>
</div><!-- fragment --></div><!-- contents -->
<div class="ttc" id="anamespacetest__builtin__casters_html_a60ceadcddedff98a968a458fec3a1fc1"><div class="ttname"><a href="namespacetest__builtin__casters.html#a60ceadcddedff98a968a458fec3a1fc1">test_builtin_casters.x</a></div><div class="ttdeci">x</div><div class="ttdef"><b>Definition:</b> <a href="test__builtin__casters_8py_source.html#l00467">test_builtin_casters.py:467</a></div></div>
<div class="ttc" id="aclass_my_exception3_html_aaa5389018cace55ea0c5b89c4f2c15f8"><div class="ttname"><a href="class_my_exception3.html#aaa5389018cace55ea0c5b89c4f2c15f8">MyException3::MyException3</a></div><div class="ttdeci">MyException3(MyException3 &amp;&amp;)=default</div></div>
<div class="ttc" id="astruct_python_already_set_in_destructor_html_a2d863c983b4f0b3d5857e23203fd42dc"><div class="ttname"><a href="struct_python_already_set_in_destructor.html#a2d863c983b4f0b3d5857e23203fd42dc">PythonAlreadySetInDestructor::~PythonAlreadySetInDestructor</a></div><div class="ttdeci">~PythonAlreadySetInDestructor()</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00079">test_exceptions.cpp:79</a></div></div>
<div class="ttc" id="aclass_my_exception3_html"><div class="ttname"><a href="class_my_exception3.html">MyException3</a></div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00031">test_exceptions.cpp:31</a></div></div>
<div class="ttc" id="astruct_python_call_in_destructor_html_a31f3a6f3e208e088742f96db98bbb553"><div class="ttname"><a href="struct_python_call_in_destructor.html#a31f3a6f3e208e088742f96db98bbb553">PythonCallInDestructor::d</a></div><div class="ttdeci">py::dict d</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00072">test_exceptions.cpp:72</a></div></div>
<div class="ttc" id="aclass_my_exception2_html"><div class="ttname"><a href="class_my_exception2.html">MyException2</a></div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00022">test_exceptions.cpp:22</a></div></div>
<div class="ttc" id="aclass_my_exception3_html_a5927c6264e4814f9fe092b0c33e054a1"><div class="ttname"><a href="class_my_exception3.html#a5927c6264e4814f9fe092b0c33e054a1">MyException3::MyException3</a></div><div class="ttdeci">MyException3(const char *m)</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00033">test_exceptions.cpp:33</a></div></div>
<div class="ttc" id="astruct_python_call_in_destructor_html_a11090c7ca44f6e43bad3a03412c82dbd"><div class="ttname"><a href="struct_python_call_in_destructor.html#a11090c7ca44f6e43bad3a03412c82dbd">PythonCallInDestructor::~PythonCallInDestructor</a></div><div class="ttdeci">~PythonCallInDestructor()</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00070">test_exceptions.cpp:70</a></div></div>
<div class="ttc" id="aclass_my_exception5_html_a10ef0850e42ccce182bbc1e9021f5369"><div class="ttname"><a href="class_my_exception5.html#a10ef0850e42ccce182bbc1e9021f5369">MyException5::MyException5</a></div><div class="ttdeci">MyException5(const std::string &amp;what)</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00060">test_exceptions.cpp:60</a></div></div>
<div class="ttc" id="aclass_my_exception4_html_a92d0b8dac77b24447648c218f01d58ae"><div class="ttname"><a href="class_my_exception4.html#a92d0b8dac77b24447648c218f01d58ae">MyException4::what</a></div><div class="ttdeci">const char * what() const noexcept override</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00051">test_exceptions.cpp:51</a></div></div>
<div class="ttc" id="aclass_my_exception3_html_a5a38e76944b26f7cba26d13384502649"><div class="ttname"><a href="class_my_exception3.html#a5a38e76944b26f7cba26d13384502649">MyException3::operator=</a></div><div class="ttdeci">MyException3 &amp; operator=(const MyException3 &amp;)=default</div></div>
<div class="ttc" id="astruct_python_already_set_in_destructor_html"><div class="ttname"><a href="struct_python_already_set_in_destructor.html">PythonAlreadySetInDestructor</a></div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00077">test_exceptions.cpp:77</a></div></div>
<div class="ttc" id="astruct_python_already_set_in_destructor_html_ae0b6a18a28340298ba02754e21225fe8"><div class="ttname"><a href="struct_python_already_set_in_destructor.html#ae0b6a18a28340298ba02754e21225fe8">PythonAlreadySetInDestructor::PythonAlreadySetInDestructor</a></div><div class="ttdeci">PythonAlreadySetInDestructor(const py::str &amp;s)</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00078">test_exceptions.cpp:78</a></div></div>
<div class="ttc" id="astruct_python_call_in_destructor_html_a3bd241ae5d0c2432978dd95c10f8c908"><div class="ttname"><a href="struct_python_call_in_destructor.html#a3bd241ae5d0c2432978dd95c10f8c908">PythonCallInDestructor::PythonCallInDestructor</a></div><div class="ttdeci">PythonCallInDestructor(const py::dict &amp;d)</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00069">test_exceptions.cpp:69</a></div></div>
<div class="ttc" id="aclass_my_exception4_html_a7c1361aa20152bdba906a5d029ee1f19"><div class="ttname"><a href="class_my_exception4.html#a7c1361aa20152bdba906a5d029ee1f19">MyException4::MyException4</a></div><div class="ttdeci">MyException4(const char *m)</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00050">test_exceptions.cpp:50</a></div></div>
<div class="ttc" id="astruct_python_already_set_in_destructor_html_a020fc31e0ab99d1662aaf93e5ffacf88"><div class="ttname"><a href="struct_python_already_set_in_destructor.html#a020fc31e0ab99d1662aaf93e5ffacf88">PythonAlreadySetInDestructor::s</a></div><div class="ttdeci">py::str s</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00090">test_exceptions.cpp:90</a></div></div>
<div class="ttc" id="aclass_my_exception3_html_a56081da37152bc94294300508d9943d3"><div class="ttname"><a href="class_my_exception3.html#a56081da37152bc94294300508d9943d3">MyException3::~MyException3</a></div><div class="ttdeci">virtual ~MyException3()=default</div></div>
<div class="ttc" id="aclass_my_exception_html_ad889306542c787a984839153b9e8462f"><div class="ttname"><a href="class_my_exception.html#ad889306542c787a984839153b9e8462f">MyException::what</a></div><div class="ttdeci">const char * what() const noexcept override</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00016">test_exceptions.cpp:16</a></div></div>
<div class="ttc" id="aclass_my_exception2_html_a6e566f7a585007a1f6f6b009acfc696c"><div class="ttname"><a href="class_my_exception2.html#a6e566f7a585007a1f6f6b009acfc696c">MyException2::what</a></div><div class="ttdeci">const char * what() const noexcept override</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00025">test_exceptions.cpp:25</a></div></div>
<div class="ttc" id="aclass_my_exception5_html"><div class="ttname"><a href="class_my_exception5.html">MyException5</a></div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00058">test_exceptions.cpp:58</a></div></div>
<div class="ttc" id="aclass_my_exception2_html_aaf4559b3dfb7b8d164708d92c3c57730"><div class="ttname"><a href="class_my_exception2.html#aaf4559b3dfb7b8d164708d92c3c57730">MyException2::MyException2</a></div><div class="ttdeci">MyException2(const char *m)</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00024">test_exceptions.cpp:24</a></div></div>
<div class="ttc" id="aclass_my_exception5__1_html"><div class="ttname"><a href="class_my_exception5__1.html">MyException5_1</a></div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00064">test_exceptions.cpp:64</a></div></div>
<div class="ttc" id="aclass_my_exception3_html_a7f94bec36360fef4942847e6859f6f05"><div class="ttname"><a href="class_my_exception3.html#a7f94bec36360fef4942847e6859f6f05">MyException3::what</a></div><div class="ttdeci">virtual const char * what() const noexcept</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00034">test_exceptions.cpp:34</a></div></div>
<div class="ttc" id="apybind11__tests_8h_html"><div class="ttname"><a href="pybind11__tests_8h.html">pybind11_tests.h</a></div></div>
<div class="ttc" id="aclassargs_html"><div class="ttname"><a href="classargs.html">args</a></div><div class="ttdef"><b>Definition:</b> <a href="pytypes_8h_source.html#l01366">pytypes.h:1366</a></div></div>
<div class="ttc" id="atest__exceptions_8cpp_html_a2f500ba7c1af71bd5a5ff919bfa99632"><div class="ttname"><a href="test__exceptions_8cpp.html#a2f500ba7c1af71bd5a5ff919bfa99632">TEST_SUBMODULE</a></div><div class="ttdeci">TEST_SUBMODULE(exceptions, m)</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00094">test_exceptions.cpp:94</a></div></div>
<div class="ttc" id="aclass_my_exception3_html_a7cf3fa1a11667d918a3ffd75ec484805"><div class="ttname"><a href="class_my_exception3.html#a7cf3fa1a11667d918a3ffd75ec484805">MyException3::MyException3</a></div><div class="ttdeci">MyException3(const MyException3 &amp;)=default</div></div>
<div class="ttc" id="aclass_my_exception_html"><div class="ttname"><a href="class_my_exception.html">MyException</a></div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00013">test_exceptions.cpp:13</a></div></div>
<div class="ttc" id="apybind11_8h_html_a0a77063d21919c13ddfeb8caf29eef59"><div class="ttname"><a href="pybind11_8h.html#a0a77063d21919c13ddfeb8caf29eef59">register_exception_translator</a></div><div class="ttdeci">void register_exception_translator(ExceptionTranslator &amp;&amp;translator)</div><div class="ttdef"><b>Definition:</b> <a href="pybind11_8h_source.html#l01991">pybind11.h:1991</a></div></div>
<div class="ttc" id="aclass_my_exception_html_abfe694fd781fe4301432e27e7dcfa249"><div class="ttname"><a href="class_my_exception.html#abfe694fd781fe4301432e27e7dcfa249">MyException::MyException</a></div><div class="ttdeci">MyException(const char *m)</div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00015">test_exceptions.cpp:15</a></div></div>
<div class="ttc" id="anamespacetest__async_html_a01702d406cc3c32308b15cbd61e86f4d"><div class="ttname"><a href="namespacetest__async.html#a01702d406cc3c32308b15cbd61e86f4d">test_async.m</a></div><div class="ttdeci">m</div><div class="ttdef"><b>Definition:</b> <a href="test__async_8py_source.html#l00005">test_async.py:5</a></div></div>
<div class="ttc" id="astruct_python_call_in_destructor_html"><div class="ttname"><a href="struct_python_call_in_destructor.html">PythonCallInDestructor</a></div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00068">test_exceptions.cpp:68</a></div></div>
<div class="ttc" id="aclass_my_exception3_html_a862afaec6b831a6298f6c1e500423aac"><div class="ttname"><a href="class_my_exception3.html#a862afaec6b831a6298f6c1e500423aac">MyException3::operator=</a></div><div class="ttdeci">MyException3 &amp; operator=(MyException3 &amp;&amp;)=default</div></div>
<div class="ttc" id="aclass_my_exception4_html"><div class="ttname"><a href="class_my_exception4.html">MyException4</a></div><div class="ttdef"><b>Definition:</b> <a href="test__exceptions_8cpp_source.html#l00048">test_exceptions.cpp:48</a></div></div>
<div class="ttc" id="apybind11_8h_html_a62bcafa97abdcadb6520a62e52331b89"><div class="ttname"><a href="pybind11_8h.html#a62bcafa97abdcadb6520a62e52331b89">print</a></div><div class="ttdeci">PYBIND11_NOINLINE void print(tuple args, dict kwargs)</div><div class="ttdef"><b>Definition:</b> <a href="pybind11_8h_source.html#l02056">pybind11.h:2056</a></div></div>
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by &#160;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/>
</a> 1.8.19
</small></address>
</body>
</html>
